### ISSUE TITLE
0.1+ Roadmap

### ISSUE THREAD

**Issue by fdecampredon** [TypeStrong/tspms#4]
- [ ] Integration with code coverage tools
- [ ] Integration with travis-ci
- [ ] integration with tslint 
- [ ] externalize the concat-declarations tools ?
- [ ] integration with tsconfig
- [ ] investigate interface pertinence over atom-typescript
- [ ] Contributing.md
- [ ] Examples
- [ ] Project pages ?
